services:
  mysql:
    image: mysql:8.0-bookworm
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: wqm
      MYSQL_USER: example_user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - Monitoring-app

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/wqm
      DB_USERNAME: example_user
      DB_PASSWORD: password123
    networks:
      - Monitoring-app

  frontend:
    build: .
    container_name: frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - Monitoring-app

volumes:
  mysql_data:

networks:
  Monitoring-app:
    driver: bridge

